# docker compose for local development

services:
  prepit-media-server:
    build:
      context: ./audio_processing
    volumes:
      - ./prepit_media_unprocessed:/app/unprocessed_media:rw
      - ./prepit_media_processed:/app/processed_media:rw
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=audio_processing
    deploy:
      replicas: 3  # Number of instances to run
  prepit-media-api:
    build:
      context: ./media_api
    volumes:
      - ./prepit_media_unprocessed:/app/unprocessed_media:rw
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=audio_processing
    ports:
      - 8000:5002
  rabbitmq:
    image: rabbitmq:3.13.3-management
    ports:
      - 15672:15672
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq:rw

