# docker compose for local development

services:
  prepit-media-server:
    build:
      context: ./audio_processing
    volumes:
      - ./prepit_media_volume:/app/volume_cache:rw
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=audio_processing
    deploy:
      replicas: 3  # Number of instances to run
  prepit-media-api:
    build:
      context: ./media_api
    volumes:
      - ./prepit_media_volume:/app/volume_cache:rw
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=audio_processing
    ports:
      - 8000:5002
  rabbitmq:
    image: rabbitmq:3.13.3-management
    ports:
      - 15672:15672
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq

# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

